### ISSUE TITLE
Edit for clarity

### ISSUE THREAD

**Issue by kellyeryan** [learn-co-curriculum/phrg-nested-tags-and-attributes#2]
Its aesthetics, how it looks, is conveying its structure. 

// could be rewritten more clearly - 

Its aesthetics, i.e. how it looks, conveys its structure.

@garettarrowood

**Comment by garettarrowood** [comment]
Resolved in https://github.com/learn-co-curriculum/phrg-nested-tags-and-attributes/commit/1448c1f86eb81f08b4b73bb260c67aa1c9698ea4
